platform :ios, '6.0'

xcodeproj 'KRLCollectionViewGridLayoutDemo'

pod 'KRLCollectionViewGridLayout', :path => "../KRLCollectionViewGridLayout.podspec"

target :KRLCollectionViewGridLayoutTests do
    pod 'OCMockito'
end
